version: "3.8"

services:
  n8n:
    image: "n8nio/n8n:${N8N_TAG:-latest}"
    env_file:
      - .env
    # Bind to localhost; Nginx is the public entrypoint
    ports:
      - "127.0.0.1:${N8N_PORT:-5678}:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
    restart: unless-stopped
    user: "0:0"

networks:
  default:
    name: n8n_net
